name = "Santa Biblia — Reina Valera 1909"
short_name = "SpaRV"
id = "santa_biblia_reina_valera_1909"
license = "https://ebible.org/Scriptures/details.php?id=spaRV1909"
language = "spa"

[books]
Gen = "Génesis"
Exod = "Éxodo"
Lev = "Levítico"
Num = "Números"
Deut = "Deuteronomio"
Josh = "Josué"
Judg = "Jueces"
Ruth = "Rut"
1Sam = "1 Samuel"
2Sam = "2 Samuel"
1Kgs = "1 Reyes"
2Kgs = "2 Reyes"
1Chr = "1 Crónicas"
2Chr = "2 Crónicas"
Ezra = "Esdras"
Neh = "Nehemías"
Esth = "Ester"
Job = "Job"
Ps = "Salmos"
Prov = "Proverbios"
Eccl = "Eclesiastés"
Song = "Cantar de los Cantares"
Isa = "Isaías"
Jer = "Jeremías"
Lam = "Lamentaciones"
Ezek = "Ezequiel"
Dan = "Daniel"
Hos = "Oseas"
Joel = "Joel"
Amos = "Amós"
Obad = "Abdías"
Jonah = "Jonás"
Mic = "Miqueas"
Nah = "Nahum"
Hab = "Habacuc"
Zeph = "Sofonías"
Hag = "Hageo"
Zech = "Zacarías"
Mal = "Malaquías"
Matt = "San Mateo"
Mark = "Marcos"
Luke = "San Lucas"
John = "Juan"
Acts = "Hechos"
Rom = "Romanos"
1Cor = "1 Corintios"
2Cor = "2 Corintios"
Gal = "Gálatas"
Eph = "Efesios"
Phil = "Filipenses"
Col = "Colosenses"
1Thess = "1 Tesalonicenses"
2Thess = "2 Tesalonicenses"
1Tim = "1 Timoteo"
2Tim = "2 Timoteo"
Titus = "Tito"
Phlm = "Filemón"
Heb = "Hebreos"
Jas = "Santiago"
1Pet = "1 Pedro"
2Pet = "2 Pedro"
1John = "1 Juan"
2John = "2 Juan"
3John = "3 Juan"
Jude = "Judas"
Rev = "Apocalipsis"
