name = "Adam Clarke Bible Commentary"
short_name = "Adam Clarke"
id = "adam_clarke_bible_commentary"
license = "https://creativecommons.org/publicdomain/mark/1.0/"
language = "eng"
data_source = "https://en.wikipedia.org/wiki/Adam_Clarke"
