name = "Biblia Takatifu"
short_name = "ULB"
license = "https://ebible.org/Scriptures/details.php?id=swhulb"
id = "biblia_takatifu_ulb"
language = "swh"

[books]
Gen = "Mwanzo"
Exod = "Kutoka"
Lev = "Mambo ya Walawi"
Num = "Hesabu"
Deut = "Kumbukumbu la Torati"
Josh = "Yoshua"
Judg = "Waamuzi"
Ruth = "Ruth"
1Sam = "1 Samweli"
2Sam = "2 Samweli"
1Kgs = "1 Wafalme"
2Kgs = "2 Wafalme"
1Chr = "1 Mambo ya Nyakati"
2Chr = "2 Mambo ya Nyakati"
Ezra = "Ezra"
Neh = "Nehemia"
Esth = "Esta"
Job = "Ayubu"
Ps = "Zaburi"
Prov = "Mithali"
Eccl = "Mhubiri"
Song = "Wimbo wa Sulemani"
Isa = "Isaya"
Jer = "Yeremia"
Lam = "Maombolezo"
Ezek = "Ezekieli"
Dan = "Danieli"
Hos = "Hosea"
Joel = "Joeli"
Amos = "Amosi"
Obad = "Obadia"
Jonah = "Yona"
Mic = "Mika"
Nah = "Nahumu"
Hab = "Habakuki"
Zeph = "Sefania"
Hag = "Hagai"
Zech = "Zekaria"
Mal = "Malaki"
Matt = "Mathayo"
Mark = "Marko"
Luke = "Luka"
John = "Yohana"
Acts = "Matendo ya Mitume"
Rom = "Warumi"
1Cor = "1 Wakorintho"
2Cor = "2 Wakorintho"
Gal = "Wagalatia"
Eph = "Waefeso"
Phil = "Wafilipi"
Col = "Wakolosai"
1Thess = "1 Wathesalonike"
2Thess = "2 Wathesalonike"
1Tim = "1 Timotheo"
2Tim = "2 Timotheo"
Titus = "Tito"
Phlm = "Filemoni"
Heb = "Wahebrania"
Jas = "Waraka wa Yakobo"
1Pet = "1 Petro"
2Pet = "2 Petro"
1John = "1 Yohana"
2John = "2 Yohana"
3John = "3 Yohana"
Jude = "Yuda"
Rev = "Ufunuo"
